version: '4.32'

services:
  frontend:
    build: ./frontend
    ports:
      - "${DOCKER_FRONT_EXTERNAL_PORT}:${DOCKER_FRONT_INTERNAL_PORT}"
    environment:
      - NODE_ENV=production

  mysql:
    image: mysql:8.0
    ports:
      - "${DOCKER_MYSQL_EXTERNAL_PORT}:${DOCKER_MYSQL_INTERNAL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "${DOCKER_BACK_EXTERNAL_PORT}:${DOCKER_BACK_INTERNAL_PORT}"
    environment:
      - NODE_ENV=production
      - DOCKER_DB_HOST=${DOCKER_DB_HOST}

volumes:
  mysql-data:
